CREATE TABLE WORK_ORDER_VALIDATION_HISTORY (
        ID INT PRIMARY KEY AUTO_INCREMENT,
        WORK_ORDER_TYPE VARCHAR(255) ,
        DEPARTMENT VARCHAR(255) ,
        VALID BIT NOT NULL,
        CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
